### ISSUE TITLE
default cron job time ?

### ISSUE THREAD

**Issue by rohan-birtia** [ckotzbauer/sbom-operator#199]
Hi, can you please provide information upon which time interval by-default the cron job runs, and which fortmat currently in quartz or liunx standard.

**Comment by ckotzbauer** [comment]
Hi @rohan-birtia,
currently there's no default cron-time on operator- or helm-chart side. Only if you deploy with the [manifest](https://github.com/ckotzbauer/sbom-operator/blob/main/deploy/standard/deployment.yaml#L32) there's still a example value for the cron defined.
So if you deploy the sbom-operator with default settings, the scheduling will use a realtime CacheInformer instead of the cron. See https://github.com/ckotzbauer/sbom-operator#analysis-trigger (there's also a link to the used library with the format explained)
